import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./components/Navbar";
import Gradient from "./components/Gradient";


export const metadata: Metadata = {
  title: "Mandlacx",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="relative jakartaFont bg-gradient-to-b from-[#151515] to-[#000000]">
        <Gradient />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
